### ISSUE TITLE
Feature Request: Add a spinner animation for pending WaitFor apps

### ISSUE THREAD

**Issue by jeremyclarke** [SecondSonConsulting/Baseline#116]
Hi, really like Baseline - thank you for making it available.

I primarily use `WaitFor` and let my MDM handle the installs. While Baseline is waiting for the WaitFor paths to appear, there doesn't seem to be any icons showing at the right of the list row, that is until they finally flip to ✅.

Would you consider an optional setting to show an “in progress” (spinner) indicator for WaitFor items that are still undetected, like there seems to be for other install types? This would give end users clearer feedback that Baseline is actively waiting rather than stalled.

Many thanks

**Comment by BigMacAdmin** [comment]
Hi Jeremy, You'll be happy to know that the spinny wait things will return in the next Baseline release, it's already been added into the current development cycle. You can read the [in-progress release notes here](https://github.com/SecondSonConsulting/Baseline/blob/dev/ReleaseNotes_2.4beta1.md).

No package yet for this beta in-progress, but you can test using the script in the `dev` branch.

**Comment by jeremyclarke** [comment]
Hey @BigMacAdmin - many thanks. Look forward to this hitting production.

**Comment by BigMacAdmin** [comment]
It's ready for testing if you want to give it a whirl and let me know. https://github.com/SecondSonConsulting/Baseline/releases/tag/2.4beta1

**Comment by danielgird** [comment]
> It's ready for testing if you want to give it a whirl and let me know. https://github.com/SecondSonConsulting/Baseline/releases/tag/2.4beta1

@BigMacAdmin 
I just tried myself (2.4beta1) and unfortunately, nothing seems to have changed, I don't see a spinner or any status icon for my pending WaitFor items. 
Is there any other prerequisite in the mobileconfig file to allow this, or a possible conflict ?

If useful, see below some specific attributes I'm currently using that could be related:
```
			<key>InstallomatorSwiftDialogIntegration</key>
			<true/>
			<key>ProgressBar</key>
			<true/>
			<key>ProgressBarDisplayNames</key>
			<true/>
			<key>WaitForTimeout</key>
			<integer>86400</integer>
```

Thank you again for your app and your great support!

**Comment by BigMacAdmin** [comment]
Hi Daniel,

You're absolutely right, I spotted something missing. Thank you for testing!

I now have this working on my test environment, if you could please also test?

You'll need to run this version of the script in the `WaitForPending` github branch: https://github.com/SecondSonConsulting/Baseline/blob/WaitForPending/Baseline.sh

and you'll want to add this key to your profile `PendingWaitForIcon` . If you want the "Spinny" you'll use `wait` if you want the grey circle with dots pending icon use `pending`  - If you don't include this key in your profile, there will be no waiting/pending icons used.

If you can try running this script and confirm, I'll release an updated package that includes this change.

Hope this makes sense, if you want more direct help hop on the [Mac Admins Slack](https://www.macadmins.org/) Baseline channel

**Comment by danielgird** [comment]
Thank you! Not tested "Spinny" yet. I have quickly tested using "pending" and it works, I see the static grey circle with 3 dots !

However, not sure if my memories are wrong, but it is not the same dynamic icon in the shape of a spinning circle that I remember it was in previous versions. By any chance, Is the "Wait" spinny setting a dynamic/moving icon?

**Comment by BigMacAdmin** [comment]
I believe you want `waiting` for the spinny thing. These are built-in SwiftDialog "Status Options" you can read about here: https://swiftdialog.app/advanced/item-lists/#status-options

v3.0+ of Dialog will also accept SF Symbols

**Comment by danielgird** [comment]
> I believe you want `waiting` for the spinny thing. These are built-in SwiftDialog "Status Options" you can read about here: https://swiftdialog.app/advanced/item-lists/#status-options
> 
> v3.0+ of Dialog will also accept SF Symbols

Finally I tested this time using "wait" instead of "pending" and I confirm the dynamic spinning icons are back ! 
Thank you again !

**Comment by jeremyclarke** [comment]
Hi both,

Sorry for such a long delay with my testing. 
I did get round to testing with the updated version of the script (2.4beta2). The spinny icons works great! But, for some reason, the very first item in the list is shown as blank with an error icon. Do you see the same? I've tried it twice.

BTW - I added this to my config:

        <key>PendingWaitForIcon</key>
        <string>wait</string>

Many thanks!

![Image](https://github.com/user-attachments/assets/9d42f017-f644-47ec-82fe-36c19b870377)

**Comment by danielgird** [comment]
Hi,
If 2.4Beta2 is 2.4Beta1 merged with the provided Baseline.sh file above, no I don't have this issue and my config uses Initial script, Installomator pkg, normal packges and indeed Waitfor items.
But it's interesting...
Did you check if Outlook is really the first item in your configuration file, in other words is there a real missing/hidden item or it's a total ghost one?

**Comment by BigMacAdmin** [comment]
OK, sorry for confusion related to the betas and which version etc.

Looks like the only branch with a working "spinny" feature right this second is the `WaitForPending` branch.

I am NOT seeing this empty line item in my testing, like Daniel said, I think this is a problem with your config file. Open in a text editor and make sure you don't have an empty entry in your array, or an empty "DisplayName" for your first item.

I am, however, seeing another issue related to WaitFor items, where no progress is being displayed until the first item on the list is successful, then all other items get checked. This is a logic issue, and I'll be working on it this week prior to release.

**Comment by jeremyclarke** [comment]
Thank you, but I don't think I have an empty entry...here's what I am using:

[baseline.mobileconfig.txt](https://github.com/user-attachments/files/25525365/baseline.mobileconfig.txt)

**Comment by BigMacAdmin** [comment]
@jeremyclarke on lines 36-42 you actually have an empty entry for a Scripts line:
```
                <key>Scripts</key>
                <array>
                    <dict>
                        <key>AsUser</key>
                        <false />
                    </dict>
                </array>

```

**Comment by jeremyclarke** [comment]
Resolved, thanks!

**Comment by danielgird** [comment]
Hello,
The spinny icons worked great, however I have finally migrated from 2.4"Beta2" to 3.0 and unfortunately I still have a similar issue with all the pending WaitFor items, no icons appear for these anymore.

Is there something new to add/change in the managed policy? 
(PendingWaitForIcon is still set to "wait", I have kept the exact same policy)

Let me know please if you want me to create a dedicated new issue for this.

Obviously SwiftDialog also been upgraded from 2.5.6 to 3.0.1 at the same time (could be related?).

Thank you and have a great day!

**Comment by BigMacAdmin** [comment]
I won't rule out that I made a manual mistake when merging changes before release, so I'm re-opening this to test and address during the next dev cycle.

@danielgird for now, if 2.4beta2 is working for you, then stick with it. There are no significant changes in Baseline 3.0 for you
